### ISSUE TITLE
v1.5 roadmap question

### ISSUE THREAD

**Issue by tryhp3** [thomaslevesque/WpfAnimatedGif#14]
I need the new feature from v1.5 but this is only beta version.
When is the planned release of the stable version?

**Comment by thomaslevesque** [comment]
> I need the new feature from v1.5

You mean synchronized animations? I never finalized it, because it introduced regressions that I was unable to fix. I ported the optimizations and fixes back to 1.4.x, but I dropped synchronized animations. I no longer plan to implement this feature, sorry...

Basically, this library is now in maintenance mode; I'll continue to fix bugs, but I will probably not add any new features to it. I'm now working on its successor: [XamlAnimatedGif](https://github.com/thomaslevesque/XamlAnimatedGif). It uses a technique completely different from the one used in WpfAnimatedGif, and it will probably be much easier to support synchronized animations in this new library. If you want it, I suggest you create an issue for it.

**Comment by tryhp3** [comment]
I mean:
"Optimized for the case where the same GIF is displayed multiple times (don't recreate the animation)"
My application takes a large amount of RAM without it.

**Comment by thomaslevesque** [comment]
This optimization has been ported back to 1.4.x, so you shouldn't see any difference with 1.5 in terms of memory usage. But even with this optimization, it will use a lot of RAM anyway, especially is the image is large and/or has many frames. This was one of my main reasons to create XamlAnimatedGif.

**Comment by tryhp3** [comment]
Thanks for info.
